name: Manuel Geri Bildirim Gönder
on:
  workflow_dispatch:
    inputs:
      masa_adi:
        description: 'Gönderilecek Masayı Seçin'
        required: true
        type: choice
        options:
          - "Masa 12"
          - "Masa 15"
          - "Masa 18"
          - "Masa 20"
          - "Masa 21"
          - "Masa 22"
          - "Masa 73"
          - "Masa 82"
          - "Masa 83"
          - "Masa 85"
          - "Masa 86"
          - "Masa 87"
          - "Masa 89"
          - "Masa 90"
          - "Masa 91"
          - "Masa 93"
          - "Masa 112"
          - "Masa 113"
          - "Masa 115B"
          - "Masa 117"
          - "Masa 118"
          - "Masa 144"
      garson_adi:
        description: 'Garson Adı Yazın'
        required: true
      cinsiyet:
        description: 'Cinsiyet Seçin'
        required: true
        type: choice
        options:
          - 'Rastgele'
          - 'Erkek'
          - 'Kadın'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Bağımlılıkları Kur
        run: pip install selenium faker webdriver-manager
      - name: Botu Çalıştır
        run: |
          python -c "from bot_core import ana_gorev_calistir; from config import MASA_LINKLERI; print(ana_gorev_calistir(MASA_LINKLERI['${{ github.event.inputs.masa_adi }}'], '${{ github.event.inputs.cinsiyet }}', '${{ github.event.inputs.garson_adi }}'))"
